### ISSUE TITLE
Wrong format in README

### ISSUE THREAD

**Issue by itztli** [giccunam/dynamicsystems2022#1] opened 2022-03-29 16:53 UTC
The README file have a bad format in the list of contributors.

**Comment by nuviedo** [comment] 2022-03-29 17:22
Can reproduce, there exists an issue in the current README.md file, mainly due to the lack of the usage of quotation markdown syntax.

> In example...

**Comment by nuviedo** [comment] 2022-04-19 16:02
Fixed in latest commit.
Closing.

**Closed as completed by nuviedo** 2022-04-19 16:02 UTC
Labels: documentation
